library(metan)
library(carData)
library(car)
library(agricolae)
View(Alexis)
str(Alexis)
Alexis = as_factor(.data= Alexis, c(Treatment, Site, Season, Replication))
str(Alexis)
model <- lm(Alexis$Severity~ Replication + Treatment + Site + Season + Site/Treatment + Season/Treatment + Site/Season/Treatment, data = Alexis)
anova(model)
boxplot(Alexis$Severity)
cv.model(model)
shapiro.test(Alexis$Severity)
wilcox.test(Alexis$, Alexis$Season, paired = T)
